### PR TITLE
PhpSpec 5 compatibility

### PR DESCRIPTION
**Pull request by roukmoute**

### CODE REVIEW

**Comment by roukmoute** [comment]
@mlopes please :innocent:

**Review by pamil — APPROVED** [review]

**Comment by pamil** [comment]
PHP 7 job needs to be removed from Travis CI in order to make tests pass.

**Comment by mlopes** [comment]
@roukmoute happy to merge when the build is passing :)

**Comment by ciaranmcnulty** [comment]
yeah @roukmoute modify the `.travis.yml` too

**Comment by roukmoute** [comment]
Sorry I didn't pay attention about that.

I've added a new commit for PHP 7.2 compatibility.

**Pull request merged**
