### PR TITLE
Add PhpSpec 6.0 support.

### PR DESCRIPTION
**Pull request by ptondereau**
Add support of phpspec 6 with a support of 5 as well.

### CODE REVIEW

**Comment by ptondereau** [comment]
@mlopes ?

**Comment by DonCallisto** [comment]
It would be great to having this merged as PHPSpec6.1 was released and add PHP7.4 support officially.
In this case also php version should be bumped to `^7.2`

**Comment by DonCallisto** [comment]
Thanks!

**Comment by DonCallisto** [comment]
@mlopes could you also tag a new version? Thanks

**Comment by mlopes** [comment]
done, sorry, the release process is a manual step, takes a few minutes to do :)

**Comment by DonCallisto** [comment]
Yeah no worry, didn't know if you thought about a new release or not and wanted just to be sure.
Thanks again!

**Pull request merged**
